vich_uploader:
    db_driver: orm
    mappings:
        services_images:
            uri_prefix: '/images/services'
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true